version: '3.3'
services:

  frontend:
    container_name: yeti-frontend
    build:
      dockerfile: ./docker-frontend/Dockerfile
    image: yetiplatform/yeti-frontend:latest
    ports:
      - 8081:80
    volumes:
      - ./docker-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    container_name: yeti-api
    image: yetiplatform/yeti:latest
    build:
      dockerfile: ./docker-yeti/Dockerfile
    env_file:
      - ${YETI_DOCKER_ENVFILE}
    entrypoint:
      - /docker-entrypoint.sh
    command: ["webserver"]
    ports:
      - 8000:8000
    depends_on:
      - redis
      - arangodb
    volumes:
      - /tmp/docker-yeti-exports:/opt/yeti/exports
      - /data/app/yeti.conf:/app/yeti.conf

  tasks:
    container_name: yeti-tasks
    image: yetiplatform/yeti:latest
    build:
      dockerfile: ./docker-yeti/Dockerfile
    env_file:
      - ${YETI_DOCKER_ENVFILE}
    command: ['tasks']
    depends_on:
      - redis
      - arangodb
      - api

  redis:
    container_name: yeti-redis
    image: redis:latest

  arangodb:
    container_name: yeti-arangodb
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=
    volumes:
      - /data/app/yeti-data:/var/lib/arangodb3

networks:
  default:
    name: yeti_network
